export const stories = [
  {
    profileImg: "/stories/profile-1.png",
    profileName: "LeetCode",
    title: ["Mastering DSA", "one problem", "at a time"],
    linkLabel: "View Profile",
    linkSrc: "https://leetcode.com/u/souravjena2003/",
    storyImg: "/stories/story-1.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Next.js",
    title: ["Building secure", "full-stack apps", "with Next.js"],
    linkLabel: "View Projects",
    linkSrc: "/work",
    storyImg: "/stories/story-2.jpg",
  },
  {
    profileImg: "/stories/profile-3.png",
    profileName: "MongoDB",
    title: ["Designing optimized", "database schemas", "for performance"],
    linkLabel: "View Projects",
    linkSrc: "/work",
    storyImg: "/stories/story-3.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "GitHub",
    title: ["Shipping code", "and collaborating", "with the community"],
    linkLabel: "View GitHub",
    linkSrc: "https://github.com/SOURAVJENA2003",
    storyImg: "/stories/story-4.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Razorpay",
    title: ["Seamless payment", "integrations for", "modern platforms"],
    linkLabel: "View Work",
    linkSrc: "/work",
    storyImg: "/stories/story-5.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "KIIT Univ",
    title: ["Pursuing excellence", "in Computer Science", "Engineering"],
    linkLabel: "Learn More",
    linkSrc: "/studio",
    storyImg: "/stories/story-6.jpg",
  },
];
